@startuml
@startuml
actor       Players       as Foo
participant Spilstart as Foo1
participant Die as Foo2
participant Points as Foo3

Foo -> Foo1 : name()
Foo -> Foo1 : fiftyFifty
Foo1 --> Foo : math.random() \nint: mønt
loop Points < 40
Foo -> Foo2 : roll()
Foo2 -> Foo3 : FaceValue()
Foo <-- Foo3 : points.Add()
end
alt players points > 39
loop player1.Points = player2.points
Foo -> Foo2 : roll()
Foo2 -> Foo3 : FaceValue()
Foo <-- Foo3 : points.Add()
end
end


@enduml


@enduml
